### ISSUE TITLE
Corrections with regards to SCI in README

### ISSUE THREAD

**Issue by borkdude** [bsless/contextual#23]
Hi! Would you mind correcting a few things in the contextual README with regards to SCI?

You mention that it is a two-phase interpreter with analysis + evaluation. This is also what SCI does: it has a distinct analysis phase where it sets up an structure for efficient evaluation (not exposed) and this can then be evaluated many times. The analysis (in sci.impl.analyzer) happens only once for an expression, not every time the expression is invoked.

The benchmark doesn't really reflect this. E.g. `eval-form` does analysis + evaluation. To properly benchmark you should be using this:
https://github.com/borkdude/sci#benchmarking
Or just evaluate a function and then benchmark running that function.

"Zero interpretation" isn't really accurate: even if the AST interprets itself, it still interprets itself and this isn't free.

An example benchmark of `(let [x 1 y 2] (+ x y))`. I think the `530ns` is the value you should compare the benchmark with from your README.

```
$ clojure -M:bench --complete --sexpr "(let [x 1 y 2] (+ x y))" --quick
BENCHMARKING EXPRESSION: (let [x 1 y 2] (+ x y))
PARSE:
-> (let [x 1 y 2] (+ x y))
Evaluation count : 570258 in 6 samples of 95043 calls.
             Execution time mean : 1,214346 µs
    Execution time std-deviation : 262,630270 ns
   Execution time lower quantile : 1,050320 µs ( 2,5%)
   Execution time upper quantile : 1,652821 µs (97,5%)
                   Overhead used : 6,595571 ns

Found 1 outliers in 6 samples (16,6667 %)
	low-severe	 1 (16,6667 %)
 Variance from outliers : 64,1922 % Variance is severely inflated by outliers
ANALYSIS:
Evaluation count : 90408 in 6 samples of 15068 calls.
             Execution time mean : 6,743714 µs
    Execution time std-deviation : 107,776153 ns
   Execution time lower quantile : 6,623334 µs ( 2,5%)
   Execution time upper quantile : 6,864625 µs (97,5%)
                   Overhead used : 6,595571 ns
EVALUATION:
-> 3
Evaluation count : 1268184 in 6 samples of 211364 calls.
             Execution time mean : 530,297082 ns
    Execution time std-deviation : 75,368344 ns
   Execution time lower quantile : 472,405178 ns ( 2,5%)
   Execution time upper quantile : 622,061292 ns (97,5%)
                   Overhead used : 6,595571 ns
```

**Comment by bsless** [comment]
Off course!
Can't promise I'll get to it right away, but in the next week or so
